spring.application.name=seconddz

info.app.name=First Spring Boot
info.app.version=1.0.0
info.app.description=???????? ?????? ?? ????
info.app.author=?????????

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
